name: Cron

on:
  # Trigger on completion of the scheduled_builds.yml file (only on main)
  workflow_run:
    workflows: [Scheduled build triggerer]
  # Manual runs through the web UI and also non-main cron job triggering
  workflow_dispatch:
  # We also want this workflow triggered if the 'Run cron CI' label is added
  # or present when PR is updated
  pull_request:
    types:
      - synchronize
      - labeled
  # We want this workflow to always run on release branches as well as
  # all tags since we want to be really sure we don't introduce
  # regressions on the release branches, and it's also important to run
  # this on pre-release and release tags.
  push:
    branches:
      - 'main'
      - '*.*'
      - '!*backport*'
    tags:
      - 'v*'
      - '!*dev*'
      - '!*pre*'
      - '!*post*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  cron:
    # Run on all triggers other than pull_request unless there's a label
    if: (github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'Run cron CI'))
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@main
    with:
      default_python: '3.12'
      submodules: false
      coverage: codecov
      toxdeps: tox-pypi-filter
      envs: |
        - linux: py311-devdeps
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
