name: Matrix Notify

on:
  workflow_run:
    types:
      - completed
    workflows:
      - CI
      - Cron

jobs:
  notify:
    # Only notify if the triggering event on the workflow which triggered this
    # workflow was "cron"
    if: |
      (github.event.workflow_run.event == 'workflow_dispatch' || github.event.workflow_run.event == 'workflow_run') &&
      (github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure')
    runs-on: ubuntu-latest
    steps:
      - uses: Cadair/matrix-notify-action@main
        with:
          matrix_token: ${{ secrets.matrix_access_token }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          homeserver: ${{ secrets.matrix_homeserver }}
          roomid: '!JYqfIVJjWANcHnfktY:cadair.com'
          ignore_pattern: '.*Load.*'
          summarise_success: true
          workflow_description: ${{ github.event.workflow_run.name }}
