name: Scheduled build triggerer

on:
  # Allow manual runs through the web UI
  workflow_dispatch:
  schedule:
    #        ┌───────── minute (0 - 59)
    #        │ ┌───────── hour (0 - 23)
    #        │ │ ┌───────── day of the month (1 - 31)
    #        │ │ │ ┌───────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────── day of the week (0 - 6 or SUN-SAT)
    - cron: '0 7 * * 1,3,5'  # Every Mon,Wed,Fri at 07:00 UTC

jobs:
  if: github.repository == 'sunpy/sunpy'
  dispatch_release_branches:
  strategy:
    fail-fast: false
    matrix:
      include:
        - branch: 6.0
        - branch: 6.1
    runs-on: ubuntu-latest
    steps:
      - run: gh workflow run ci.yml --repo sunpy/sunpy --ref ${{ matrix.branch }}
      - run: gh workflow run cron.yml --repo sunpy/sunpy --ref ${{ matrix.branch }}
    env:
      GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
